import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./font.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Captain Side Gaming",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + "text-white"} >{children}</body>
    </html>
  );
}
